name: golangci-lint
description: Run golangci-lint to lint and format Go code in your Buildkite pipeline
author: https://github.com/buildkite-plugins
requirements:
  - bash
configuration:
  properties:
    use_docker:
      type: boolean
      description: "Use Docker to run golangci-lint. If false, golangci-lint must be available in $PATH. Defaults to `true`."
      default: true
    docker_image:
      type: string
      description: "Docker image to use for golangci-lint. Defaults to `golangci/golangci-lint:latest`."
      default: "golangci/golangci-lint:latest"
    mount_git:
      type: boolean
      description: "Mount .git directory into Docker container. Enables VCS stamping and git-based linters. Defaults to `true`."
      default: true
    ignore_linter_errors:
      type: boolean
      description: "Whether to ignore linter errors and allow the step to pass. Defaults to `false`."
      default: false
    create_annotations:
      type: boolean
      description: "Create Buildkite annotations to display linter results. Defaults to `true`."
      default: true
    run_formatter:
      type: boolean
      description: "Run golangci-lint fmt command to check Go source file formatting. Defaults to `false`."
      default: false
    ignore_formatter_errors:
      type: boolean
      description: "Whether to ignore formatter errors and allow the step to pass. Only applies if run_formatter is true. Defaults to `false`."
      default: false
    timeout:
      type: string
      description: "Timeout for golangci-lint run command (e.g., '5m', '1h')."
    config:
      type: string
      description: "Path to golangci-lint config file."
    issues_exit_code:
      type: number
      description: "Exit code when issues are found. Defaults to 1."
      default: 1
    cache_dir:
      type: string
      description: "Directory to use for golangci-lint cache."
    working_directory:
      type: string
      description: "Working directory to run golangci-lint in. Defaults to current directory."
  additionalProperties: false
